#!/usr/bin/env python3
"""
scripts/4_caption_audio.py

Generates natural-language music captions for every audio file using
Qwen2-Audio-7B-Instruct — the same model used by the challenge organisers
to produce the evaluation test prompts.

Qwen2-Audio is an *auxiliary* component (audio language model for captioning).
Pre-trained weights are permitted under challenge rules.

Usage:
    python scripts/4_caption_audio.py \
        --audio_dir  ../mtg_jamendo_separated \
        --output_dir ../mtg_captions \
        [--model_name Qwen/Qwen2-Audio-7B-Instruct] \
        [--batch_size 1] \
        [--device cuda] \
        [--overwrite]

Output layout mirrors the input:
    mtg_captions/
    ├── 00/
    │   ├── 1234500.txt    # one-line natural language caption
    │   └── ...
    └── ...

Prompt engineering note:
    The challenge test prompts are generated by asking Qwen2-Audio to describe
    musical concept tags (genre, instrumentation, mood). We therefore use the
    same style here — asking the model to produce a caption under 100 words
    in the "description" style rather than "command" style.
"""

import argparse
import sys
from pathlib import Path

import torch
import torchaudio
from tqdm import tqdm


CAPTION_PROMPT = (
    "Listen to this instrumental music clip carefully. "
    "Write a concise music description in one sentence (under 100 words) "
    "covering genre, instrumentation, tempo, mood, and texture. "
    "Use a descriptive caption style such as: "
    "'A mellow jazz piece featuring piano and bass, calm and relaxed in tone.' "
    "Do NOT use instruction-style phrasing. "
    "Do NOT mention vocals or singing — this is an instrumental track."
)


def parse_args():
    p = argparse.ArgumentParser(description="Generate captions for ATTM training audio")
    p.add_argument("--audio_dir",   required=True)
    p.add_argument("--output_dir",  required=True)
    p.add_argument("--model_name",  default="Qwen/Qwen2-Audio-7B-Instruct",
                   help="HuggingFace model ID for the audio LM")
    p.add_argument("--batch_size",  type=int, default=1,
                   help="Qwen2-Audio processes 1 file at a time by default")
    p.add_argument("--sample_rate", type=int, default=16000,
                   help="Qwen2-Audio expects 16kHz mono audio")
    p.add_argument("--max_duration",type=float, default=10.0,
                   help="Clip length to send to the model (10s is usually enough for genre/mood)")
    p.add_argument("--device",      default="cuda" if torch.cuda.is_available() else "cpu")
    p.add_argument("--overwrite",   action="store_true")
    return p.parse_args()


def load_audio_16k(path: Path, target_sr: int, max_duration: float):
    """Load, resample to 16kHz mono, trim. Returns numpy array or None."""
    try:
        wav, sr = torchaudio.load(str(path))
        if wav.shape[0] > 1:
            wav = wav.mean(dim=0, keepdim=True)           # stereo → mono
        if sr != target_sr:
            resampler = torchaudio.transforms.Resample(sr, target_sr)
            wav = resampler(wav)
        max_samples = int(max_duration * target_sr)
        wav = wav[0, :max_samples]                        # (T,)
        return wav.numpy()
    except Exception as e:
        print(f"  [WARN] Could not load {path}: {e}", file=sys.stderr)
        return None


def main():
    args = parse_args()

    audio_dir  = Path(args.audio_dir)
    output_dir = Path(args.output_dir)

    if not audio_dir.exists():
        sys.exit(f"[ERROR] audio_dir does not exist: {audio_dir}")

    extensions = {".mp3", ".wav", ".flac", ".ogg"}
    audio_files = sorted([p for p in audio_dir.rglob("*") if p.suffix.lower() in extensions])

    if not audio_files:
        sys.exit(f"[ERROR] No audio files found in {audio_dir}")

    print(f"Found {len(audio_files):,} audio files.")

    # Filter already-captioned
    if not args.overwrite:
        todo = [
            af for af in audio_files
            if not (output_dir / af.relative_to(audio_dir)).with_suffix(".txt").exists()
        ]
        skipped = len(audio_files) - len(todo)
        if skipped:
            print(f"Skipping {skipped:,} already-captioned files.")
        audio_files = todo

    if not audio_files:
        print("Nothing to do.")
        return

    # ── Load Qwen2-Audio (auxiliary captioning model) ──
    print(f"\nLoading {args.model_name}...")
    print("  (This downloads ~15 GB on first run — requires ~20 GB VRAM for inference)")

    from transformers import AutoProcessor, Qwen2AudioForConditionalGeneration
    import numpy as np

    processor = AutoProcessor.from_pretrained(args.model_name)
    model_q   = Qwen2AudioForConditionalGeneration.from_pretrained(
        args.model_name,
        torch_dtype=torch.float16 if "cuda" in args.device else torch.float32,
        device_map=args.device,
    )
    model_q.eval()
    print(f"  → Loaded on {args.device}\n")

    errors    = 0
    processed = 0

    for af in tqdm(audio_files, unit="file", desc="Captioning"):
        wav_np = load_audio_16k(af, args.sample_rate, args.max_duration)
        if wav_np is None:
            errors += 1
            continue

        # Build Qwen2-Audio conversation
        conversation = [
            {
                "role": "user",
                "content": [
                    {"type": "audio", "audio_url": "__placeholder__"},
                    {"type": "text",  "text": CAPTION_PROMPT},
                ],
            }
        ]

        try:
            text_input = processor.apply_chat_template(
                conversation, add_generation_prompt=True, tokenize=False
            )
            inputs = processor(
                text=text_input,
                audios=[wav_np],
                sampling_rate=args.sample_rate,
                return_tensors="pt",
            ).to(args.device)

            with torch.inference_mode():
                generated_ids = model_q.generate(
                    **inputs,
                    max_new_tokens=128,
                    do_sample=False,
                )

            # Decode only the newly generated tokens
            input_len = inputs["input_ids"].shape[1]
            caption   = processor.decode(
                generated_ids[0, input_len:],
                skip_special_tokens=True,
            ).strip()

        except Exception as e:
            print(f"  [WARN] Caption failed for {af.name}: {e}", file=sys.stderr)
            errors += 1
            continue

        # Write caption
        rel   = af.relative_to(audio_dir)
        out_f = (output_dir / rel).with_suffix(".txt")
        out_f.parent.mkdir(parents=True, exist_ok=True)
        out_f.write_text(caption, encoding="utf-8")
        processed += 1

    print(f"\n{'='*60}")
    print(f" Captioning complete!")
    print(f"   Processed : {processed:,}")
    print(f"   Errors    : {errors:,}")
    print(f"   Output    : {output_dir}")
    print(f"\n Next step: python training/train_flow.py --config configs/flow_default.yaml --use_default_captions False")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
